'use client';

import { useEffect, useState, type ReactElement } from 'react';

import { useArtifactVersions } from '@/hooks/chat/useThreadArtifacts';
import {
  artifactService,
  type ArtifactVersion,
} from '@/services/artifactService';
import {
  useArtifactPanelStore,
  type Artifact,
} from '@/store/artifactPanelStore';

import { ArtifactFileView } from './ArtifactFileView';
import { formatBytes } from './ArtifactPreview';

type GeneratedArtifact = Extract<Artifact, { kind: 'generated' }>;

/**
 * Panel body for a generated file: version history (newest first), the
 * selected version's provenance line, and a read-only preview. Switching a
 * version re-targets the same panel entry; nothing is edited here.
 */
export function GeneratedArtifactBody({
  artifact,
}: {
  artifact: GeneratedArtifact;
}): ReactElement {
  const { data, isLoading, isError, refetch } = useArtifactVersions(
    artifact.artifactId
  );
  const openArtifact = useArtifactPanelStore((s) => s.openArtifact);
  // Keyed by version so a failure never carries over to another file.
  const [downloadFailedFor, setDownloadFailedFor] = useState<string | null>(
    null
  );
  const downloadFailed = downloadFailedFor === artifact.versionId;

  if (isLoading) {
    return (
      <div role="status" className="p-4 text-sm text-muted-foreground">
        Loading…
      </div>
    );
  }
  if (isError || !data) {
    return (
      <div role="alert" className="p-4 text-sm">
        <p>Could not load this file’s versions.</p>
        <button
          type="button"
          className="mt-3 rounded-md border px-3 py-2 text-sm"
          onClick={() => void refetch()}
        >
          Retry
        </button>
      </div>
    );
  }
  const versions = [...data].reverse();
  const selected = data.find((v) => v.versionId === artifact.versionId);
  if (!selected) {
    // A card can name a version newer than the cached list; refetch rather
    // than silently showing an older one.
    return (
      <div role="status" className="p-4 text-sm text-muted-foreground">
        <p>Loading the requested version…</p>
        <RefetchOnce refetch={refetch} />
      </div>
    );
  }
  const index = data.findIndex((v) => v.versionId === selected.versionId) + 1;
  return (
    <div className="flex h-full flex-col">
      <div className="flex flex-wrap items-center gap-2 border-b px-4 py-2 text-xs text-muted-foreground">
        <label className="flex items-center gap-2">
          <span>Version</span>
          <select
            aria-label="Artifact version"
            className="rounded-md border bg-background px-2 py-1 text-xs text-foreground"
            value={selected.versionId}
            onChange={(event) => {
              const next = data.find((v) => v.versionId === event.target.value);
              openArtifact(
                {
                  ...artifact,
                  versionId: event.target.value,
                  title: next?.title ?? artifact.title,
                },
                { source: 'user' }
              );
            }}
          >
            {versions.map((v) => (
              <option key={v.versionId} value={v.versionId}>
                v{data.findIndex((x) => x.versionId === v.versionId) + 1} ·{' '}
                {new Date(v.createdAt).toLocaleString()}
              </option>
            ))}
          </select>
        </label>
        <span aria-label="Provenance">
          v{index} · {producerLabel(selected)} · {selected.mimeType} ·{' '}
          {formatBytes(selected.byteSize)}
        </span>
        <button
          type="button"
          className="ml-auto rounded-md border px-2 py-1 text-xs text-foreground"
          onClick={() => {
            setDownloadFailedFor(null);
            artifactService
              .downloadVersion(selected)
              .catch(() => setDownloadFailedFor(selected.versionId));
          }}
        >
          Download
        </button>
        {downloadFailed && <span role="alert">Download failed.</span>}
      </div>
      <div className="min-h-0 flex-1 overflow-auto">
        <ArtifactFileView version={selected} />
      </div>
    </div>
  );
}

function producerLabel(version: ArtifactVersion): string {
  if (version.producer === 'harness') return 'Published by Codex';
  if (version.producer === 'nous') return 'Generated by NOUS';
  // No author identity in the DTO; any editor may have published it.
  return 'Published by a project member';
}

/** Fires one refetch on mount; keeps the effect out of the parent's render path. */
function RefetchOnce({ refetch }: { refetch: () => unknown }): null {
  useEffect(() => {
    void refetch();
  }, [refetch]);
  return null;
}
